name: CI-CD Backend Pipeline

on:
  workflow_dispatch:

jobs:
  ci-cd-backend:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: ./5_days_in_the_clouds_2024-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Set up EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Add EF Core CLI to PATH
        run: echo "${{ github.workspace }}/.dotnet/tools" >> $GITHUB_PATH

      - name: Install NuGet packages
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}/5_days_in_the_clouds_2024.API/5_days_in_the_clouds_2024.API.csproj

      - name: Build main project
        run: dotnet build ${{ env.WORKING_DIRECTORY }}/5_days_in_the_clouds_2024.API/5_days_in_the_clouds_2024.API.csproj --configuration Release

      - name: Publish application
        run: dotnet publish ${{ env.WORKING_DIRECTORY }}/5_days_in_the_clouds_2024.API/5_days_in_the_clouds_2024.API.csproj --configuration Release --output ${{ env.WORKING_DIRECTORY }}/publish

      - name: Get agent public IP
        id: get-ip
        shell: bash
        run: |
          echo "Fetching public IP…"
          AGENT_IP=$(curl -s http://ipinfo.io/ip)
          echo "AGENT_IP=$AGENT_IP" >> $GITHUB_ENV

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: fetch Azure Key Vault secrets
        id: fetch-secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ vars.AZURE_KEY_VAULT_NAME }}
          secrets: sql-admin,sql-password

      - name: Add Agent IP to SQL server firewall
        shell: bash
        run: |
          az sql server firewall-rule create \
            --resource-group ${{ vars.AZURE_SQL_RESOURCE_GROUP }} \
            --server ${{ vars.AZURE_SQL_SERVER_NAME }} \
            --name AllowGitHubActions \
            --start-ip-address $AGENT_IP \
            --end-ip-address   $AGENT_IP

      - name: Apply EF Core migrations
        run: |
          echo "Applying EF Core migrations…"
          dotnet ef database update --project ${{ env.WORKING_DIRECTORY }}/5_days_in_the_clouds_2024.Infrastructure/5_days_in_the_clouds_2024.Infrastructure.csproj --context AppDbContext --connection "Server=tcp:${{ vars.AZURE_SQL_SERVER_NAME }}.database.windows.net,1433;Initial Catalog=${{ vars.AZURE_SQL_DATABASE_NAME }};Persist Security Info=False;User ID=${{ steps.fetch-secrets.outputs.sql-admin }};Password=${{ steps.fetch-secrets.outputs.sql-password }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

      - name: Remove Agent IP from SQL firewall
        if: always()
        shell: bash
        run: |
          az sql server firewall-rule delete \
          --resource-group ${{ vars.AZURE_SQL_RESOURCE_GROUP }} \
          --server ${{ vars.AZURE_SQL_SERVER_NAME }} \
          --name AllowGitHubActions

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: lwa-eteamslevi9-be-dev-eun-001
          package: ${{ env.WORKING_DIRECTORY }}/publish
