name: CI-CD AZ-Function Storage Pipeline

on:
  workflow_dispatch:

jobs:
  ci-cd-az-function-storage:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: ./5_days_in_the_clouds_2024-az-functions/MatchStorage.Function

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install NuGet packages
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}/MatchStorage.Function/MatchStorage.Function.csproj

      - name: Build main project
        run: dotnet build ${{ env.WORKING_DIRECTORY }}/MatchStorage.Function/MatchStorage.Function.csproj --configuration Release

      - name: Publish application
        run: dotnet publish ${{ env.WORKING_DIRECTORY }}/MatchStorage.Function/MatchStorage.Function.csproj --configuration Release --output ${{ env.WORKING_DIRECTORY }}/publish

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: func-eteamslevi9-dev-eun-001-foo
          package: ${{ env.WORKING_DIRECTORY }}/publish
